### PR TITLE
AMLS905X4-742: Some APIs in device info are returning 'ERROR_GENERAL'

### PR DESCRIPTION
**Pull request by liginPunoose**
Reason for change: add additional resolutions in DeviceInfo json file in Thunder 4.2

Test Procedure: Build and verify

Risks: Low

### CODE REVIEW

**Comment by liginPunoose** [comment]
Please help to merge this PR on R4_4 branch. This is for R4 specific and a separate PR for master will be made later based on the study.

**Review by karuna2git — APPROVED** [review]

**Comment by karuna2git** [comment]
Hi @MFransen69,
Could you please review and merge this for R4.4.2 release.
Thanks,

**Review by MFransen69 — APPROVED** [review]

**Comment by MFransen69** [comment]
> Hi @MFransen69, Could you please review and merge this for R4.4.2 release. Thanks,

Merged to master and will make sure it gets cherrypicked to 4.4

**Comment by MFransen69** [comment]
@karuna2git 
Sorry, missed it was a PR on 4_4 directly. And as the file in master does not have this and other changes (e.g. the whole enumvalues field is missing) are you sure you do not want to update the one in master? (otherwise these changes will be missing from R5)

**Comment by karuna2git** [comment]
I requested @liginPunoose  to create PR that suits for master as well.

**Pull request merged**
