### PR TITLE
DELIA-57107: Split IDeviceCapabilities

### PR DESCRIPTION
**Pull request by npoltorapavlo**
Reason for change: Separation of concern
Test Procedure: None
Risks: Low
Signed-off-by: Nikita Poltorapavlo <npoltorapavlo@productengine.com>

### CODE REVIEW

**Comment by pwielders** [comment]
Interfaces are a contract between different parties. If you start changing the contract you need to be aware that "all" parties involved get changed. 
I think your assumption is that the implementation of this interface in the DevicePlugin is the "only" party as it is used for running the plugin out of process. 
However this interface has more parties (consumers) see: https://github.com/rdkcentral/ThunderClientLibraries/tree/master/Source/deviceinfo 

Good practice in software development is to deprecate an interface in favor of a new one but not remove it in one go. This way it does not go like a big bang through all component and there is time to upgrade.  The new interface looks oke and it is a good idea to split it up but I do think that you should maintain backwards compatibility and for a certain period of time support both. Using COMRPC this is not difficult and it is what COMRPC, implementation of Microsofts COM philosophy,  is all aimed for, see: https://www.oreilly.com/library/view/com-programming-with/1565928407/ch06s03.html.
So suggest to maintain both interfaces so we have time to upgrade all parties committed to these software contracts and in the future remove the deprecated interface.

**Review by pwielders — CHANGES_REQUESTED** [review]
Backwards compatibility broken. The ClientLibraries/DeviceInfo will be broken if this interface is applied.

**Comment by npoltorapavlo** [comment]
Thanks @pwielders . I've added IDeviceInfo2.h and reverted IDeviceInfo.h to the original for backwards compatibility

**Comment by pwielders** [comment]
@npoltorapavlo seems there is already quite some difference between R2 and R3/R4. I will align this internally here to make sure the IDeviceInfo2 gets correctly populated on R3/R4 and than in due time we can clear out the IDeviceInfo.h.

**Review by pwielders — APPROVED** [review]

**Pull request merged**
