### PR TITLE
RDK-35050: PersistentStore interface

### PR DESCRIPTION
**Pull request by npoltorapavlo**
Reason for change: Store can be queried via interface.
Interface for notifications.
Test Procedure: Unit tests.
Risks: Low
Signed-off-by: Nikita Poltorapavlo <npoltorapavlo@productengine.com>

### CODE REVIEW

**Review by anand-ky — COMMENTED** [review]
looks good.

**Comment by anand-ky** [comment]
@pwielders @karuna2git - Pls review and help merge. This is the IStore interface for the PersistentStore plugin under RDKServices.

**Review by karuna2git — DISMISSED** [review]
Hi @anand-ky  and @npoltorapavlo ,
The change looks good to me.

In RDK, we are using R2 branch; not MASTER branch. Could you please bring it to R2. We can merge it there.

For master, @pwielders  will review and merge

**Comment by npoltorapavlo** [comment]
#127

**Review by pwielders — CHANGES_REQUESTED** [review]
Conceptually the interface has some flaws. As the interface hints that it can be used over process boundaries (inherits from IUnknown) it can not be used over process boundaries. If it is a C++ interface (to be used in process and just to hookup libraries in 1 process) it is fine but than please remove the ID and the inheritance from IUnknown)
For process agnostic behaviour, you can only use scalar valus and interfaces. You can not use std::vector<>/stad::map<> as parameters.
The interfaces has a-symetric behaviour, there is an open but no close ?
It has a dual purpose (no real seperation of concern). Looks like it services bahaviour (FlushCache/Term/FGetStorageSize) and data functionality (Set/Get).
Also since this requires, probably exposure on JSONRPC, the interface signature do not allow for automatic creation of the JSONRPC interface, which might be usefull.
Looking at the methods, I think there is already such an interface (and implementation) available and it is called thge Dictionary plugin. The interface is here: https://github.com/rdkcentral/ThunderInterfaces/blob/master/interfaces/IDictionary.h, the implemetation is here: https://github.com/rdkcentral/ThunderNanoServices/tree/master/Dictionary. The plugin is dated prior to the enhancements of the JSONRPC generator, so it also lacks the auomatic generation of JSONRPC, but maybe we could just extend it whith that functionality.

Where will this interface be used? What is the plugin?

**Comment by npoltorapavlo** [comment]
This interface is for the plugin https://github.com/rdkcentral/rdkservices/blob/sprint/2201/PersistentStore/doc/PersistentStorePlugin.md and has the same APIs plus Open and Term. The latter is for close. Will serializing std::vector<>/std::map<> to a std::string make it process agnostic?

**Comment by pwielders** [comment]
@npoltorapavlo still missing feedback on the comment? Why not use the Dictionary plugin (less dependencies, probably faster, as it does not roundtrip to a DB, and a smaller footprint) and if you do not want to use the plugin, why not at least use the interface  (IDictionary), it has a better seperation of conern and does work over process boundaries.

If you stick to this interfaces, indeed passing a string would resolve the issue (not the dual functionality bit, for that IO suggest to split up the interface in2 interfaces, QueryInterface allows you to access both) but please also answer my questions above, why not use the Dictionary plugin ?

**Comment by npoltorapavlo** [comment]
PersistentStore and Dictionary are different. I don't need IDictionary. The idea was to make PersistentStore accessible via an interface. Because, for example, the RDKShell plugin uses PersistentStore via JSON-RPC. The functionality of IStore looks good to me. I think this is what users of this interface would expect. I can check how to replace std::vector<>/std::map<> if this is the main concern.

**Comment by pwielders** [comment]
From my perspective the Dictionary plugin is a KeyValue persistent store as is the PersisteStore plugin (at least what I saw from it) also the keys in both plugins are stored in a namspace so I think at least a large part (if not all) of the functionality is overlapping.

Just wanted to mention it , to avoid later the statement "why did you not tell us" 😄 .

Anyhow, the implementation request is driven from Comcast/RDK and if they do not consider the "sepeartion of concern" on interface exposure as being an issue, and the interface is only intended for class-separation (only used inthe same process), the interface is good as is and happy to approve. @anand-ky / @karuna2git

**Comment by npoltorapavlo** [comment]
Removed std::vector<>/std::map<> and Open/Term from the interface, as requested.

**Review by pwielders — APPROVED** [review]

**Pull request merged**
