### PR TITLE
RDK-34729: Display APIs to DeviceInfo

### PR DESCRIPTION
**Pull request by npoltorapavlo**
Reason for change: Add methods as below.
- defaultresolution (string videoDisplay) ->
  enum defaultResolution
- supportedresolutions (string videoDisplay) ->
  array of enum supportedResolutions
- supportedhdcp (string videoDisplay) ->
  enum supportedHDCPVersion
- displaysettings (string videoDisplay) ->
  int colorSpace, int colorDepth, int matrixCoefficients,
  int videoEOTF, int quantizationRange
- audiocapabilities (string audioPort) ->
  array of enum AudioCapabilities
- ms12capabilities (string audioPort) ->
  array of enum MS12Capabilities
- supportedms12audioprofiles (string audioPort) ->
  array of enum supportedMS12AudioProfiles
Add properties as below.
- supportedaudioports ->
  array of string supportedAudioPorts
- supportedvideodisplays ->
  array of string supportedVideoDisplays
- hostedid ->
  string EDID
Test Procedure: Test DeviceInfo RDK Service.
Risks: Low
Signed-off-by: Nikita Poltorapavlo <npoltorapavlo@productengine.com>

### CODE REVIEW

**Comment by pwielders** [comment]
I think this is a bit of a mixture between what was discussed and what would be added to the DeviceInfo plugin and what would be on the DisplayInfo plugin.
The agreement was that device specific settings (like supported resolutions) would be on the deviceInfo, as these are depicted/controlled/allowed by the STB. Information specific to the HDMI connection and the display should be on the DisplayINfo. That means that for example hostedid should be served from the DisplayInfo.
So I guess we need to split this interface from device specific settings and display specific setting.

**Comment by npoltorapavlo** [comment]
Dropped displaysettings as it's not device specific. Other settings including "host" edid work without display connected, I assume they are device specific.

**Comment by npoltorapavlo** [comment]
@pwielders, the requested changes have been addressed. Please proceed with review

**Comment by anand-ky** [comment]
@pwielders - Pls help review so that we can merge to meet sprint deadlines.

**Review by pwielders — APPROVED** [review]

**Pull request merged**
