### PR TITLE
[PackMan] Introduction of IPackageManager interface

### PR DESCRIPTION
**Pull request by MFransen69**
This is a copy of the ILISA interface, for now changes are only introduced to be able to generate the JSON RPC code from it, later on changes might be introduced to support other packagers

### CODE REVIEW

**Review by pwielders — DISMISSED** [review]

**Comment by mhughesacn** [comment]
Hi Marcel: BD is complaining about the RDKM header.  If this is really an RDKM file, then please add these lines to NOTICE in the top level of the component and I will clear it.  Otherwise, please use Metrological.  Thanks, Martin

Copyright 2023 RDK Management
Licensed under the Apache License, Version 2.0

**Comment by MFransen69** [comment]
> Hi Marcel: BD is complaining about the RDKM header. If this is really an RDKM file, then please add these lines to NOTICE in the top level of the component and I will clear it. Otherwise, please use Metrological. Thanks, Martin
> 
> Copyright 2023 RDK Management Licensed under the Apache License, Version 2.0

Hi Martin,

I discussed this internally before adding and as this is introduced not for Metrological itself the RDKM one seemed more appropriate. I'll add the text you refer to above.

**Review by pwielders — DISMISSED** [review]

**Comment by mhughesacn** [comment]
Hi Marcel: Crossed wires :-)
I want the copyright notice added to the file called NOTICE in the top level directory of the component, not in the file itself.
Thanks!

**Comment by MFransen69** [comment]
Ah sorry misunderstood :) Let me add it there

**Comment by MFransen69** [comment]
Fixed! (at least I hope it is correct now :) )

**Review by pwielders — APPROVED** [review]

**Pull request merged**
