### PR TITLE
RDK-48604 New UserSettings Thunder Plugin

### PR DESCRIPTION
**Pull request by sithanda**
Reason for change: Adding IUserSettings.h interface file.

Test Procedure: Build and verify

### CODE REVIEW

**Comment by mhughesacn** [comment]
Hi Sithanda:
Please add a credit for Synamedia to the NOTICE file by appending:

```
Copyright 2024 Synamedia Ltd.
Licensed under the Apache License, Version 2.0
```

Thank you - Martin Hughes, RDK CMF Compliance Team

**Review by karuna2git — DISMISSED** [review]

**Comment by sithanda** [comment]
> Hi Sithanda: Please add a credit for Synamedia to the NOTICE file by appending:
> 
> ```
> Copyright 2024 Synamedia Ltd.
> Licensed under the Apache License, Version 2.0
> ```
> 
> Thank you - Martin Hughes, RDK CMF Compliance Team

Thanks Martin, Now added the credit of synamedia in NOTICE file.

**Review by karuna2git — APPROVED** [review]

**Review by karuna2git — APPROVED** [review]

**Comment by ramasat** [comment]
Please hold the merge of this review. We have few things to be taken care before it is ready to be merged.

**Comment by sithanda** [comment]
Cancel this PR as per @ramasat comment.

**Pull request closed without merging**
